import os

models = ['python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_0_sgd --epochs 100 --select_clf 0 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_1_sgd --epochs 100 --select_clf 1 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_2_sgd --epochs 100 --select_clf 2 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_3_sgd --epochs 100 --select_clf 3 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_0_sgd --epochs 100 --select_clf 0 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_1_sgd --epochs 100 --select_clf 1 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_2_sgd --epochs 100 --select_clf 2 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_3_sgd --epochs 100 --select_clf 3 --optimizer sgd',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_0_sgd_mix --epochs 100 --select_clf 0 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_1_sgd_mix --epochs 100 --select_clf 1 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_2_sgd_mix --epochs 100 --select_clf 2 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_3_sgd_mix --epochs 100 --select_clf 3 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_0_sgd_mix --epochs 100 --select_clf 0 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_1_sgd_mix --epochs 100 --select_clf 1 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_2_sgd_mix --epochs 100 --select_clf 2 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_3_sgd_mix --epochs 100 --select_clf 3 --optimizer sgd --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_0_adam --epochs 100 --select_clf 0 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_1_adam --epochs 100 --select_clf 1 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_2_adam --epochs 100 --select_clf 2 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_3_adam --epochs 100 --select_clf 3 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_0_adam --epochs 100 --select_clf 0 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_1_adam --epochs 100 --select_clf 1 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_2_adam --epochs 100 --select_clf 2 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_3_adam --epochs 100 --select_clf 3 --optimizer adam',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_0_adam_mix --epochs 100 --select_clf 0 --optimizer adam --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_1_adam_mix --epochs 100 --select_clf 1 --optimizer adam --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_2_adam_mix --epochs 100 --select_clf 2 --optimizer adam --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet18 --filename pesos_18_3_adam_mix --epochs 100 --select_clf 3 --optimizer adam --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_0_adam_mix --epochs 100 --select_clf 0 --optimizer adam --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_1_adam_mix --epochs 100 --select_clf 1 --optimizer adam --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_2_adam_mix --epochs 100 --select_clf 2 --optimizer adam --data_augmentation mixup',
'python main.py --train --batch_size 32 --model resnet34 --filename pesos_34_3_adam_mix --epochs 100 --select_clf 3 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_0_sgd --epochs 100 --select_clf 0 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_1_sgd --epochs 100 --select_clf 1 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_2_sgd --epochs 100 --select_clf 2 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_3_sgd --epochs 100 --select_clf 3 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_0_sgd --epochs 100 --select_clf 0 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_1_sgd --epochs 100 --select_clf 1 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_2_sgd --epochs 100 --select_clf 2 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_3_sgd --epochs 100 --select_clf 3 --optimizer sgd',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_0_sgd_mix --epochs 100 --select_clf 0 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_1_sgd_mix --epochs 100 --select_clf 1 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_2_sgd_mix --epochs 100 --select_clf 2 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_3_sgd_mix --epochs 100 --select_clf 3 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_0_sgd_mix --epochs 100 --select_clf 0 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_1_sgd_mix --epochs 100 --select_clf 1 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_2_sgd_mix --epochs 100 --select_clf 2 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_3_sgd_mix --epochs 100 --select_clf 3 --optimizer sgd --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_0_adam --epochs 100 --select_clf 0 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_1_adam --epochs 100 --select_clf 1 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_2_adam --epochs 100 --select_clf 2 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_3_adam --epochs 100 --select_clf 3 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_0_adam --epochs 100 --select_clf 0 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_1_adam --epochs 100 --select_clf 1 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_2_adam --epochs 100 --select_clf 2 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_3_adam --epochs 100 --select_clf 3 --optimizer adam',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_0_adam_mix --epochs 100 --select_clf 0 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_1_adam_mix --epochs 100 --select_clf 1 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_2_adam_mix --epochs 100 --select_clf 2 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet18 --filename pesos_18_3_adam_mix --epochs 100 --select_clf 3 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_0_adam_mix --epochs 100 --select_clf 0 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_1_adam_mix --epochs 100 --select_clf 1 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_2_adam_mix --epochs 100 --select_clf 2 --optimizer adam --data_augmentation mixup',
'python main.py --test --batch_size 32 --model resnet34 --filename pesos_34_3_adam_mix --epochs 100 --select_clf 3 --optimizer adam --data_augmentation mixup']


for model in models: 
    os.system(model)


